#+title: Post Series
#+date: 
#+FILETAGS: 

* Thought for the day
  :PROPERTIES:
  :CUSTOM_ID: 20220602191239
  :END:
  Short reflections.
  * [[file:20220623212643.org][Not as the world gives]]

* Mining for Wisdom: Gems from Solomon's Quarry
  :PROPERTIES:
  :CUSTOM_ID: 20220602142630
  :END:

  Some wisdom from the books of Proverbs and Ecclesiastes.

  * [[file:20220527172601.org][If Your Strong City Is Not God]]

* Teach Like A Christian
  :PROPERTIES:
  :CUSTOM_ID: 20220602191220
  :END:
  A series of posts on Teaching as a Christian. Some reflections on how to apply Scripture to the teaching profession and also what teaching has taught me.

* Who do you say that I am?
  :PROPERTIES:
  :CUSTOM_ID: 20220602191235
  :END:

  During Jesus life on earth many people had all kinds of ideas about who He was. On one occasion Jesus asks the disciples what people were saying about Him. After fielding some responses a Jesus asks the disciples "But who do you say that I am?". And this is a question we must all answer, and will all answer one way or the other. These posts are what the bible has to say about who Jesus. OF course they will be wholy inadequate, but hopefully, they will be helpful.


