#+TODO: idea notes draft revise proof | done 


* Mining for Wisdom: Gems from Solomon

** draft If God Is Not Your Strong City                                :devo:
   - link: [[~/jd-m.github.io/posts-org/20220527172601.org]]

** idea This blessing has Fallen Upon Me                               :devo:
   - Obedience is a blessing from God.
   - It is something we look back on.
   - The blessing is past tense.
   - We cannot know whether we will be obedient until it is tested.

* Teach Like A Christian
** idea Don't discipline with Scorpions          
* Who do you say I am

  - When Jesus asked the disciples who they thought Jesus was Peter responded with what sounded like a good answer. But he later showed that what he thought he meant was not what Jesus meant. We cannot just know words about Jesus we must seek to understand what they mean if we want to understand what God tells us about Jesus through His word.

    - The Word of God
    - The Image of the Invisible God
    - The Glory of God
    - The Lamb of God
    - The Son of God
    - The Wisdom of God
* Thought for the day
** Eccelesiastes 7 
   - Better is the end of a thing than the beginning.
   - This goes for smaller things: thinking about what to do to bring the best outcome in a situation, rather than just what we are thinking in the moment is wisdom. A patient person thinks of the end. An angry person does what they feel and only thinks on the beginning.
   - It is more wisdom to live with the end in mind than the beginning
   - This may make us sorrowful, or seem sombre. It may make people think we are morbid. But if we live in light of the end we will change the way we live today.
   - Jesus encourages us to think on the end.
     - Mt: Save life - lose it. Lose life (for His sake) - save it. When He will appear with His angels in the glory of the Father.

** John 5:39
   - You search the scriptures because you think that in them you have eternal life.
